variables:
  BUILD_DIR: terraform-runner 
  IMAGE_NAME: terraform-runner  
  YANDEX_REGISTRY: cr.yandex/crprles4pfjpj44kv3fh

build-branch:
  extends: .build-branch

build_and_tag_image_master:
  extends: .build_and_tag_image_master
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

